ProcessingNode:
  ros__parameters:
    Inputs:
      MotorStromEins: ["sensor_data", "data"]
    NumberOfInputSamples:
      MotorStromEins: 100
    ModelInformation:
      ModelPath: "/root/mounted_folder/MLDeploy_Nachbau/src/inference_model/inference_model/autoencoder.onnx"
      ModelInferenceTimerPeriod: 0.5
    Extras:
      Imports: 
        ~