ProcessingNode:
  ros__parameters:
    Inputs:
      MotorStromEins: ["sensor_data", "data"]
    NumberOfInputSamples:
      MotorStromEins: 100
    ModelInformation:
      ModelPath: "/root/mounted_folder/ros_ml_deploy/src/processing_node/processing_node/autoencoder.onnx"
      ModelInferenceTimerPeriod: 0.5
    Training:
      TrainingMode: False
      TrainingSampleMultiplier: 100
      NumberOfEpochs: 20
    Extras:
      Imports: 
        ~
      