Inputs:
  MotorStromEins:
    Name: "Motorstrom 1"
    Topic: "sensor_data"
    Field: ["data"]
Outputs:
  Loss: 
    Name: "Loss"
    Topic: "CoolesTopic"
    Field: ["loss", "loss"]
    MessageType: "Sensordata"
Extras:
  Imports:
    Sensordata:
      Package: "custom_messages.msg"
      Module: "Sensordata"
      