Inputs:
  MotorStromEins:
    Name: "Motorstrom 1"
    topic: ["sensor_data", "data"]
Outputs:
  Loss: 
    Name: "Loss"
    topic: "CoolesTopic"
    field: ["loss", "loss"]
    MessageType: "Sensordata"
Extras:
  Imports:
    Sensordata:
      Package: "custom_messages.msg"
      Module: "Sensordata"
      