Inputs:
  Motorstrom 1:
    Description: "Beispielsweise Strom, der den Greifer versorgt"
    Topic: "sensor_data"
    Field: ["data"]
Outputs:
  float parameter: 
    Description: "Parameter that controls absolutely nothing"
    Topic: "CoolTopic"
    Field: ["data"]
    MessageType: "Float32"
  int parameter:
    Description: "Another parameter that controls absolutely nothing"
    Topic: "EvenCoolerTopic"
    Field: ["data"]
    MessageType: "Int16"
Extras:
  Imports:
    Float32:
      Package: "std_msgs.msg"
      Module: "Float32"
    Int16:
      Package: "std_msgs.msg"
      Module: "Int16"
      