Inputs:
  MotorStromEins:
    Name: "Motorstrom 1"
    topic: ["sensor_data", "data"]
Outputs:
  Loss: 
    Name: "Loss"
    topic: ["model_output", "loss"] 
    MessageType: "Float32"
Extras:
  Imports: 
    ~
      