Inputs:
  MotorStromEins:
    Name: "Motorstrom 1"
    topic: ["sensor_data", "data"]
Outputs:
  Loss: 
    Name: "Loss"
    topic: ["loss", "data"] 
    MessageType: "Float32"
Extras:
  Imports:
    Float32:
      Package: "std_msgs.msg"
      Module: "Float32"
      