Inputs:
  Motorstrom 1:
    Description: "Beispielsweise Strom, der den Greifer versorgt"
    Topic: "sensor_data"
    Field: ["data"]
Outputs:
  float parameter: 
    Description: "Parameter that controls absolutely nothing"
    Topic: "CoolesTopic"
    Field: ["data"]
    MessageType: "Float32"
Extras:
  Imports:
    Float32:
      Package: "std_msgs.msg"
      Module: "Float32"
      