on: push
jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - uses: ika-rwth-aachen/docker-ros@v1.3.1
        with:
          base-image: rwthika/ros2:humble
          command: python3 -m pytest -v
          image-name: ghcr.io/wbk-robotics/ros_ml_deploy
