on: push
jobs:
  docker-ros:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ika-rwth-aachen/docker-ros@v1.3.1
        with:
          base-image: rwthika/ros2:humble
          command: ros2 topic list >> $GITHUB_OUTPUT
          image-name: ghcr.io/wbk-robotics/ros_ml_deploy
          target: dev
  launch:
     runs-on: ubuntu-latest
     container:
       image: ghcr.io/wbk-robotics/ros_ml_deploy
       credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
     steps:
       - name: Testrun
         run: ros2 topic list
        
